[package]
name = "contracts"
version = "0.2.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.11.4"
openzeppelin_access = "1.0.0"
openzeppelin_token = "1.0.0"
openzeppelin_presets = "1.0.0"

[dev-dependencies]
openzeppelin_utils = "1.0.0"
snforge_std = "0.42.0"

[[target.starknet-contract]]
casm = true                                                                  # taggle this to `false` to speed up compilation/testing
build-external-contracts = ["openzeppelin_presets::erc20::ERC20Upgradeable"]

[tool.fmt]
sort-module-level-items = true

[[tool.snforge.fork]]
name = "SEPOLIA_LATEST"
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
block_id.tag = "latest"
